// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAqJV7Kz-UzQS8HD0JKRARKNztKXzYBB4',
    appId: '1:712430932679:web:174ce7dfadf5d5235ae4e2',
    messagingSenderId: '712430932679',
    projectId: 'to-do-application-68d7b',
    authDomain: 'to-do-application-68d7b.firebaseapp.com',
    storageBucket: 'to-do-application-68d7b.firebasestorage.app',
    measurementId: 'G-B2E23CNL6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI8vT3Df1Q5cIkHs3Slb-HtEzbK6TsXxE',
    appId: '1:712430932679:android:182bf1b9a1ce552a5ae4e2',
    messagingSenderId: '712430932679',
    projectId: 'to-do-application-68d7b',
    storageBucket: 'to-do-application-68d7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFoG6R1gmv148izULnE1HMhwnCV650P6s',
    appId: '1:712430932679:ios:aa2b8d990cc4facd5ae4e2',
    messagingSenderId: '712430932679',
    projectId: 'to-do-application-68d7b',
    storageBucket: 'to-do-application-68d7b.firebasestorage.app',
    iosBundleId: 'com.example.toDoFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFoG6R1gmv148izULnE1HMhwnCV650P6s',
    appId: '1:712430932679:ios:aa2b8d990cc4facd5ae4e2',
    messagingSenderId: '712430932679',
    projectId: 'to-do-application-68d7b',
    storageBucket: 'to-do-application-68d7b.firebasestorage.app',
    iosBundleId: 'com.example.toDoFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAqJV7Kz-UzQS8HD0JKRARKNztKXzYBB4',
    appId: '1:712430932679:web:95627cd17c29cb085ae4e2',
    messagingSenderId: '712430932679',
    projectId: 'to-do-application-68d7b',
    authDomain: 'to-do-application-68d7b.firebaseapp.com',
    storageBucket: 'to-do-application-68d7b.firebasestorage.app',
    measurementId: 'G-FKVD1CFTL5',
  );
}
